// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vacation_protocols.proto
// Protobuf C++ Version: 5.27.3

#include "vacation_protocols.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Vacation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : startdate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        enddate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        empid_{0},
        dayscount_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Vacation::Vacation(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct VacationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VacationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VacationDefaultTypeInternal() {}
  union {
    Vacation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VacationDefaultTypeInternal _Vacation_default_instance_;

inline constexpr GetVacationsByEmployeeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : empid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetVacationsByEmployeeRequest::GetVacationsByEmployeeRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetVacationsByEmployeeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVacationsByEmployeeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVacationsByEmployeeRequestDefaultTypeInternal() {}
  union {
    GetVacationsByEmployeeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVacationsByEmployeeRequestDefaultTypeInternal _GetVacationsByEmployeeRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR GetAllEmployeersRequest::GetAllEmployeersRequest(::_pbi::ConstantInitialized) {}
struct GetAllEmployeersRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetAllEmployeersRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetAllEmployeersRequestDefaultTypeInternal() {}
  union {
    GetAllEmployeersRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetAllEmployeersRequestDefaultTypeInternal _GetAllEmployeersRequest_default_instance_;

inline constexpr GetVacationsByEmployeeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : vacations_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetVacationsByEmployeeResponse::GetVacationsByEmployeeResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetVacationsByEmployeeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVacationsByEmployeeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVacationsByEmployeeResponseDefaultTypeInternal() {}
  union {
    GetVacationsByEmployeeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVacationsByEmployeeResponseDefaultTypeInternal _GetVacationsByEmployeeResponse_default_instance_;

inline constexpr Employee::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : vacations_{},
        firstname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        lastname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        patronymic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Employee::Employee(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EmployeeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmployeeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmployeeDefaultTypeInternal() {}
  union {
    Employee _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmployeeDefaultTypeInternal _Employee_default_instance_;

inline constexpr GetAllEmployeersResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : employees_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetAllEmployeersResponse::GetAllEmployeersResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetAllEmployeersResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetAllEmployeersResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetAllEmployeersResponseDefaultTypeInternal() {}
  union {
    GetAllEmployeersResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetAllEmployeersResponseDefaultTypeInternal _GetAllEmployeersResponse_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_vacation_5fprotocols_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_vacation_5fprotocols_2eproto = nullptr;
const ::uint32_t
    TableStruct_vacation_5fprotocols_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Vacation, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Vacation, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Vacation, _impl_.empid_),
        PROTOBUF_FIELD_OFFSET(::Vacation, _impl_.startdate_),
        PROTOBUF_FIELD_OFFSET(::Vacation, _impl_.enddate_),
        PROTOBUF_FIELD_OFFSET(::Vacation, _impl_.dayscount_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Employee, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.firstname_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.lastname_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.patronymic_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.vacations_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetAllEmployeersRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetAllEmployeersResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetAllEmployeersResponse, _impl_.employees_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetVacationsByEmployeeRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetVacationsByEmployeeRequest, _impl_.empid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetVacationsByEmployeeResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetVacationsByEmployeeResponse, _impl_.vacations_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Vacation)},
        {13, -1, -1, sizeof(::Employee)},
        {26, -1, -1, sizeof(::GetAllEmployeersRequest)},
        {34, -1, -1, sizeof(::GetAllEmployeersResponse)},
        {43, -1, -1, sizeof(::GetVacationsByEmployeeRequest)},
        {52, -1, -1, sizeof(::GetVacationsByEmployeeResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Vacation_default_instance_._instance,
    &::_Employee_default_instance_._instance,
    &::_GetAllEmployeersRequest_default_instance_._instance,
    &::_GetAllEmployeersResponse_default_instance_._instance,
    &::_GetVacationsByEmployeeRequest_default_instance_._instance,
    &::_GetVacationsByEmployeeResponse_default_instance_._instance,
};
const char descriptor_table_protodef_vacation_5fprotocols_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030vacation_protocols.proto\"\\\n\010Vacation\022\n"
    "\n\002id\030\001 \001(\005\022\r\n\005empId\030\002 \001(\005\022\021\n\tstartDate\030\003"
    " \001(\t\022\017\n\007endDate\030\004 \001(\t\022\021\n\tdaysCount\030\005 \001(\005"
    "\"m\n\010Employee\022\n\n\002id\030\001 \001(\005\022\021\n\tfirstName\030\002 "
    "\001(\t\022\020\n\010lastName\030\003 \001(\t\022\022\n\npatronymic\030\004 \001("
    "\t\022\034\n\tvacations\030\005 \003(\0132\t.Vacation\"\031\n\027GetAl"
    "lEmployeersRequest\"8\n\030GetAllEmployeersRe"
    "sponse\022\034\n\temployees\030\001 \003(\0132\t.Employee\".\n\035"
    "GetVacationsByEmployeeRequest\022\r\n\005empId\030\001"
    " \001(\005\">\n\036GetVacationsByEmployeeResponse\022\034"
    "\n\tvacations\030\001 \003(\0132\t.Vacation2\266\001\n\020Vacatio"
    "nsService\022G\n\020GetAllEmployeers\022\030.GetAllEm"
    "ployeersRequest\032\031.GetAllEmployeersRespon"
    "se\022Y\n\026GetVacationsByEmployee\022\036.GetVacati"
    "onsByEmployeeRequest\032\037.GetVacationsByEmp"
    "loyeeResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_vacation_5fprotocols_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_vacation_5fprotocols_2eproto = {
    false,
    false,
    621,
    descriptor_table_protodef_vacation_5fprotocols_2eproto,
    "vacation_protocols.proto",
    &descriptor_table_vacation_5fprotocols_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_vacation_5fprotocols_2eproto::offsets,
    file_level_enum_descriptors_vacation_5fprotocols_2eproto,
    file_level_service_descriptors_vacation_5fprotocols_2eproto,
};
// ===================================================================

class Vacation::_Internal {
 public:
};

Vacation::Vacation(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Vacation)
}
inline PROTOBUF_NDEBUG_INLINE Vacation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Vacation& from_msg)
      : startdate_(arena, from.startdate_),
        enddate_(arena, from.enddate_),
        _cached_size_{0} {}

Vacation::Vacation(
    ::google::protobuf::Arena* arena,
    const Vacation& from)
    : ::google::protobuf::Message(arena) {
  Vacation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, dayscount_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::dayscount_));

  // @@protoc_insertion_point(copy_constructor:Vacation)
}
inline PROTOBUF_NDEBUG_INLINE Vacation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : startdate_(arena),
        enddate_(arena),
        _cached_size_{0} {}

inline void Vacation::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, dayscount_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::dayscount_));
}
Vacation::~Vacation() {
  // @@protoc_insertion_point(destructor:Vacation)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Vacation::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.startdate_.Destroy();
  _impl_.enddate_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Vacation::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Vacation, _impl_._cached_size_),
              false,
          },
          &Vacation::MergeImpl,
          &Vacation::kDescriptorMethods,
          &descriptor_table_vacation_5fprotocols_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 33, 2> Vacation::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Vacation_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Vacation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Vacation, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Vacation, _impl_.id_)}},
    // int32 empId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Vacation, _impl_.empid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Vacation, _impl_.empid_)}},
    // string startDate = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Vacation, _impl_.startdate_)}},
    // string endDate = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Vacation, _impl_.enddate_)}},
    // int32 daysCount = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Vacation, _impl_.dayscount_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Vacation, _impl_.dayscount_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Vacation, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 empId = 2;
    {PROTOBUF_FIELD_OFFSET(Vacation, _impl_.empid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string startDate = 3;
    {PROTOBUF_FIELD_OFFSET(Vacation, _impl_.startdate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string endDate = 4;
    {PROTOBUF_FIELD_OFFSET(Vacation, _impl_.enddate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 daysCount = 5;
    {PROTOBUF_FIELD_OFFSET(Vacation, _impl_.dayscount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\10\0\0\11\7\0\0\0"
    "Vacation"
    "startDate"
    "endDate"
  }},
};

PROTOBUF_NOINLINE void Vacation::Clear() {
// @@protoc_insertion_point(message_clear_start:Vacation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.startdate_.ClearToEmpty();
  _impl_.enddate_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.dayscount_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.dayscount_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Vacation::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Vacation)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // int32 empId = 2;
  if (this->_internal_empid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_empid(), target);
  }

  // string startDate = 3;
  if (!this->_internal_startdate().empty()) {
    const std::string& _s = this->_internal_startdate();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Vacation.startDate");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string endDate = 4;
  if (!this->_internal_enddate().empty()) {
    const std::string& _s = this->_internal_enddate();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Vacation.endDate");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // int32 daysCount = 5;
  if (this->_internal_dayscount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_dayscount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Vacation)
  return target;
}

::size_t Vacation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Vacation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string startDate = 3;
  if (!this->_internal_startdate().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_startdate());
  }

  // string endDate = 4;
  if (!this->_internal_enddate().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_enddate());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  // int32 empId = 2;
  if (this->_internal_empid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_empid());
  }

  // int32 daysCount = 5;
  if (this->_internal_dayscount() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_dayscount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Vacation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Vacation*>(&to_msg);
  auto& from = static_cast<const Vacation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Vacation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_startdate().empty()) {
    _this->_internal_set_startdate(from._internal_startdate());
  }
  if (!from._internal_enddate().empty()) {
    _this->_internal_set_enddate(from._internal_enddate());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_empid() != 0) {
    _this->_impl_.empid_ = from._impl_.empid_;
  }
  if (from._internal_dayscount() != 0) {
    _this->_impl_.dayscount_ = from._impl_.dayscount_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Vacation::CopyFrom(const Vacation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Vacation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Vacation::InternalSwap(Vacation* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.startdate_, &other->_impl_.startdate_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.enddate_, &other->_impl_.enddate_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vacation, _impl_.dayscount_)
      + sizeof(Vacation::_impl_.dayscount_)
      - PROTOBUF_FIELD_OFFSET(Vacation, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Vacation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Employee::_Internal {
 public:
};

Employee::Employee(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Employee)
}
inline PROTOBUF_NDEBUG_INLINE Employee::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Employee& from_msg)
      : vacations_{visibility, arena, from.vacations_},
        firstname_(arena, from.firstname_),
        lastname_(arena, from.lastname_),
        patronymic_(arena, from.patronymic_),
        _cached_size_{0} {}

Employee::Employee(
    ::google::protobuf::Arena* arena,
    const Employee& from)
    : ::google::protobuf::Message(arena) {
  Employee* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:Employee)
}
inline PROTOBUF_NDEBUG_INLINE Employee::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : vacations_{visibility, arena},
        firstname_(arena),
        lastname_(arena),
        patronymic_(arena),
        _cached_size_{0} {}

inline void Employee::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Employee::~Employee() {
  // @@protoc_insertion_point(destructor:Employee)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Employee::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.firstname_.Destroy();
  _impl_.lastname_.Destroy();
  _impl_.patronymic_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Employee::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Employee, _impl_._cached_size_),
              false,
          },
          &Employee::MergeImpl,
          &Employee::kDescriptorMethods,
          &descriptor_table_vacation_5fprotocols_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 44, 2> Employee::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Employee_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Employee>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Employee, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.id_)}},
    // string firstName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.firstname_)}},
    // string lastName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.lastname_)}},
    // string patronymic = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.patronymic_)}},
    // repeated .Vacation vacations = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.vacations_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string firstName = 2;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.firstname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string lastName = 3;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.lastname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string patronymic = 4;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.patronymic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .Vacation vacations = 5;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.vacations_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Vacation>()},
  }}, {{
    "\10\0\11\10\12\0\0\0"
    "Employee"
    "firstName"
    "lastName"
    "patronymic"
  }},
};

PROTOBUF_NOINLINE void Employee::Clear() {
// @@protoc_insertion_point(message_clear_start:Employee)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.vacations_.Clear();
  _impl_.firstname_.ClearToEmpty();
  _impl_.lastname_.ClearToEmpty();
  _impl_.patronymic_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Employee::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Employee)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string firstName = 2;
  if (!this->_internal_firstname().empty()) {
    const std::string& _s = this->_internal_firstname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Employee.firstName");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string lastName = 3;
  if (!this->_internal_lastname().empty()) {
    const std::string& _s = this->_internal_lastname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Employee.lastName");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string patronymic = 4;
  if (!this->_internal_patronymic().empty()) {
    const std::string& _s = this->_internal_patronymic();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Employee.patronymic");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // repeated .Vacation vacations = 5;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_vacations_size());
       i < n; i++) {
    const auto& repfield = this->_internal_vacations().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            5, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Employee)
  return target;
}

::size_t Employee::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Employee)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .Vacation vacations = 5;
  total_size += 1UL * this->_internal_vacations_size();
  for (const auto& msg : this->_internal_vacations()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string firstName = 2;
  if (!this->_internal_firstname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_firstname());
  }

  // string lastName = 3;
  if (!this->_internal_lastname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_lastname());
  }

  // string patronymic = 4;
  if (!this->_internal_patronymic().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_patronymic());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Employee::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Employee*>(&to_msg);
  auto& from = static_cast<const Employee&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Employee)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_vacations()->MergeFrom(
      from._internal_vacations());
  if (!from._internal_firstname().empty()) {
    _this->_internal_set_firstname(from._internal_firstname());
  }
  if (!from._internal_lastname().empty()) {
    _this->_internal_set_lastname(from._internal_lastname());
  }
  if (!from._internal_patronymic().empty()) {
    _this->_internal_set_patronymic(from._internal_patronymic());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Employee::CopyFrom(const Employee& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Employee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Employee::InternalSwap(Employee* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.vacations_.InternalSwap(&other->_impl_.vacations_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.firstname_, &other->_impl_.firstname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.lastname_, &other->_impl_.lastname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.patronymic_, &other->_impl_.patronymic_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Employee::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetAllEmployeersRequest::_Internal {
 public:
};

GetAllEmployeersRequest::GetAllEmployeersRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:GetAllEmployeersRequest)
}
GetAllEmployeersRequest::GetAllEmployeersRequest(
    ::google::protobuf::Arena* arena,
    const GetAllEmployeersRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  GetAllEmployeersRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:GetAllEmployeersRequest)
}

const ::google::protobuf::MessageLite::ClassData*
GetAllEmployeersRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetAllEmployeersRequest, _impl_._cached_size_),
              false,
          },
          &GetAllEmployeersRequest::MergeImpl,
          &GetAllEmployeersRequest::kDescriptorMethods,
          &descriptor_table_vacation_5fprotocols_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> GetAllEmployeersRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetAllEmployeersRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetAllEmployeersRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata GetAllEmployeersRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetAllEmployeersResponse::_Internal {
 public:
};

GetAllEmployeersResponse::GetAllEmployeersResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetAllEmployeersResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetAllEmployeersResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GetAllEmployeersResponse& from_msg)
      : employees_{visibility, arena, from.employees_},
        _cached_size_{0} {}

GetAllEmployeersResponse::GetAllEmployeersResponse(
    ::google::protobuf::Arena* arena,
    const GetAllEmployeersResponse& from)
    : ::google::protobuf::Message(arena) {
  GetAllEmployeersResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GetAllEmployeersResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetAllEmployeersResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : employees_{visibility, arena},
        _cached_size_{0} {}

inline void GetAllEmployeersResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetAllEmployeersResponse::~GetAllEmployeersResponse() {
  // @@protoc_insertion_point(destructor:GetAllEmployeersResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetAllEmployeersResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetAllEmployeersResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetAllEmployeersResponse, _impl_._cached_size_),
              false,
          },
          &GetAllEmployeersResponse::MergeImpl,
          &GetAllEmployeersResponse::kDescriptorMethods,
          &descriptor_table_vacation_5fprotocols_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> GetAllEmployeersResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GetAllEmployeersResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetAllEmployeersResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Employee employees = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetAllEmployeersResponse, _impl_.employees_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .Employee employees = 1;
    {PROTOBUF_FIELD_OFFSET(GetAllEmployeersResponse, _impl_.employees_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Employee>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetAllEmployeersResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:GetAllEmployeersResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.employees_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetAllEmployeersResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GetAllEmployeersResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .Employee employees = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_employees_size());
       i < n; i++) {
    const auto& repfield = this->_internal_employees().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetAllEmployeersResponse)
  return target;
}

::size_t GetAllEmployeersResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetAllEmployeersResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .Employee employees = 1;
  total_size += 1UL * this->_internal_employees_size();
  for (const auto& msg : this->_internal_employees()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetAllEmployeersResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetAllEmployeersResponse*>(&to_msg);
  auto& from = static_cast<const GetAllEmployeersResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetAllEmployeersResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_employees()->MergeFrom(
      from._internal_employees());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetAllEmployeersResponse::CopyFrom(const GetAllEmployeersResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetAllEmployeersResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetAllEmployeersResponse::InternalSwap(GetAllEmployeersResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.employees_.InternalSwap(&other->_impl_.employees_);
}

::google::protobuf::Metadata GetAllEmployeersResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetVacationsByEmployeeRequest::_Internal {
 public:
};

GetVacationsByEmployeeRequest::GetVacationsByEmployeeRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetVacationsByEmployeeRequest)
}
GetVacationsByEmployeeRequest::GetVacationsByEmployeeRequest(
    ::google::protobuf::Arena* arena, const GetVacationsByEmployeeRequest& from)
    : GetVacationsByEmployeeRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetVacationsByEmployeeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetVacationsByEmployeeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.empid_ = {};
}
GetVacationsByEmployeeRequest::~GetVacationsByEmployeeRequest() {
  // @@protoc_insertion_point(destructor:GetVacationsByEmployeeRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetVacationsByEmployeeRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetVacationsByEmployeeRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetVacationsByEmployeeRequest, _impl_._cached_size_),
              false,
          },
          &GetVacationsByEmployeeRequest::MergeImpl,
          &GetVacationsByEmployeeRequest::kDescriptorMethods,
          &descriptor_table_vacation_5fprotocols_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetVacationsByEmployeeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetVacationsByEmployeeRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetVacationsByEmployeeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 empId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetVacationsByEmployeeRequest, _impl_.empid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetVacationsByEmployeeRequest, _impl_.empid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 empId = 1;
    {PROTOBUF_FIELD_OFFSET(GetVacationsByEmployeeRequest, _impl_.empid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetVacationsByEmployeeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:GetVacationsByEmployeeRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.empid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetVacationsByEmployeeRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GetVacationsByEmployeeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 empId = 1;
  if (this->_internal_empid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_empid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetVacationsByEmployeeRequest)
  return target;
}

::size_t GetVacationsByEmployeeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetVacationsByEmployeeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 empId = 1;
  if (this->_internal_empid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_empid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetVacationsByEmployeeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetVacationsByEmployeeRequest*>(&to_msg);
  auto& from = static_cast<const GetVacationsByEmployeeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetVacationsByEmployeeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_empid() != 0) {
    _this->_impl_.empid_ = from._impl_.empid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetVacationsByEmployeeRequest::CopyFrom(const GetVacationsByEmployeeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetVacationsByEmployeeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetVacationsByEmployeeRequest::InternalSwap(GetVacationsByEmployeeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.empid_, other->_impl_.empid_);
}

::google::protobuf::Metadata GetVacationsByEmployeeRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetVacationsByEmployeeResponse::_Internal {
 public:
};

GetVacationsByEmployeeResponse::GetVacationsByEmployeeResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetVacationsByEmployeeResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetVacationsByEmployeeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GetVacationsByEmployeeResponse& from_msg)
      : vacations_{visibility, arena, from.vacations_},
        _cached_size_{0} {}

GetVacationsByEmployeeResponse::GetVacationsByEmployeeResponse(
    ::google::protobuf::Arena* arena,
    const GetVacationsByEmployeeResponse& from)
    : ::google::protobuf::Message(arena) {
  GetVacationsByEmployeeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GetVacationsByEmployeeResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetVacationsByEmployeeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : vacations_{visibility, arena},
        _cached_size_{0} {}

inline void GetVacationsByEmployeeResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetVacationsByEmployeeResponse::~GetVacationsByEmployeeResponse() {
  // @@protoc_insertion_point(destructor:GetVacationsByEmployeeResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetVacationsByEmployeeResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetVacationsByEmployeeResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetVacationsByEmployeeResponse, _impl_._cached_size_),
              false,
          },
          &GetVacationsByEmployeeResponse::MergeImpl,
          &GetVacationsByEmployeeResponse::kDescriptorMethods,
          &descriptor_table_vacation_5fprotocols_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> GetVacationsByEmployeeResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GetVacationsByEmployeeResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetVacationsByEmployeeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Vacation vacations = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetVacationsByEmployeeResponse, _impl_.vacations_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .Vacation vacations = 1;
    {PROTOBUF_FIELD_OFFSET(GetVacationsByEmployeeResponse, _impl_.vacations_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Vacation>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetVacationsByEmployeeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:GetVacationsByEmployeeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.vacations_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetVacationsByEmployeeResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GetVacationsByEmployeeResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .Vacation vacations = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_vacations_size());
       i < n; i++) {
    const auto& repfield = this->_internal_vacations().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetVacationsByEmployeeResponse)
  return target;
}

::size_t GetVacationsByEmployeeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetVacationsByEmployeeResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .Vacation vacations = 1;
  total_size += 1UL * this->_internal_vacations_size();
  for (const auto& msg : this->_internal_vacations()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetVacationsByEmployeeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetVacationsByEmployeeResponse*>(&to_msg);
  auto& from = static_cast<const GetVacationsByEmployeeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetVacationsByEmployeeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_vacations()->MergeFrom(
      from._internal_vacations());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetVacationsByEmployeeResponse::CopyFrom(const GetVacationsByEmployeeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetVacationsByEmployeeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetVacationsByEmployeeResponse::InternalSwap(GetVacationsByEmployeeResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.vacations_.InternalSwap(&other->_impl_.vacations_);
}

::google::protobuf::Metadata GetVacationsByEmployeeResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_vacation_5fprotocols_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
